%name: studio_nexora
description: AI-powered professional photography mobile app
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  shimmer: ^3.0.0
  
  # State Management
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  get_it: ^7.6.4
  
  # Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2
  
  # Storage & Cache
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  
  # Image Processing
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  photo_view: ^0.14.0
  flutter_image_compress: ^2.1.0
  
  # Authentication
  clerk_flutter: ^1.0.0
  local_auth: ^2.1.8
  
  # Payments
  flutter_stripe: ^10.1.1
  in_app_purchase: ^3.1.13
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.3
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  
  # UI Components
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  modal_bottom_sheet: ^3.0.0
  pull_to_refresh: ^2.0.0
  
  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
